# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/python/black
    rev: 21.5b1
    hooks:
    -   id: black
        types: [file]
        files: \.(py|pyi)$

